"""Synapse Storm generator (spec section 8.1).

Emits a .storm file that WOULD ingest the graph into a Synapse Cortex --
this module never connects to or executes against a real Cortex; the
output is a generated, syntax-checked artifact (see
docs/storm-queries.md for the paired queries you would run against it
once ingested).

Form mapping (a documented choice, not an official Synapse schema
decision): the spec's own worked example only shows risk:threat (group)
and risk:vuln (CVE). Extending to tool/technique per this week's scope,
this module uses:
  group     -> risk:threat=(strata, <id>)          :name=<label>
  vuln      -> risk:vuln=(cve, "<CVE-id>")          :cve=<CVE-id>
  tool      -> it:prod:soft=(strata, <id>)          :name=<label>
  technique -> ou:technique=(strata, <id>)          :name=<label>
Edges emitted only between these four node types (the real edge types
that connect them: hands_off_to [group->group], uses [group->tool],
exploits [group->vuln], implements [group->technique]) -- exactly the
edge set spec 8.1's worked example anticipates, using Storm's light
arrow syntax `-(rel)>`.
"""

from __future__ import annotations

import re
import sqlite3
from datetime import UTC, datetime

_NODE_TYPES = ("group", "vuln", "tool", "technique")
_EDGE_TYPES = ("hands_off_to", "uses", "exploits", "implements")

_STORM_REL_NAME = {
    "hands_off_to": "hands-off-to",
    "uses": "uses",
    "exploits": "exploits",
    "implements": "implements",
}


def _storm_str(value: str) -> str:
    """Escape a string for embedding in a Storm double-quoted literal."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _form_ref(node_id: str, node_type: str) -> str:
    """The Storm form-reference expression for one node, e.g. risk:threat=(strata, sylvanite).

    Every node_id is quoted and escaped via _storm_str, not just vuln's --
    node_id for tool/technique/group ids ultimately derives from
    corpus-authored strings (Tool.name, Technique.attack_id, group id),
    none of which carry a regex/pattern constraint in normalize/models.py.
    An unquoted, unescaped splice here would let a crafted tool name
    (e.g. containing a stray paren, comma, or newline) break out of the
    Storm tuple syntax and corrupt the generated .storm file's structure
    -- found and fixed in security review, matching the same discipline
    the vuln branch already had.
    """
    if node_type == "vuln":
        return f'risk:vuln=(cve, "{_storm_str(node_id)}")'
    if node_type == "tool":
        return f'it:prod:soft=(strata, "{_storm_str(node_id)}")'
    if node_type == "technique":
        return f'ou:technique=(strata, "{_storm_str(node_id)}")'
    return f'risk:threat=(strata, "{_storm_str(node_id)}")'


def _node_block(node_id: str, node_type: str, label: str) -> str:
    """One [ form=... :prop=... ] node-definition block."""
    ref = _form_ref(node_id, node_type)
    if node_type == "vuln":
        return f'[ {ref}\n    :cve="{_storm_str(node_id)}"\n]'
    return f'[ {ref}\n    :name="{_storm_str(label)}"\n]'


def _edge_block(edge_type: str, src_id: str, src_type: str, dst_id: str, dst_type: str) -> str:
    """One `[ src ] -(rel)> { dst }` edge block."""
    rel = _STORM_REL_NAME[edge_type]
    src_ref = _form_ref(src_id, src_type)
    dst_ref = _form_ref(dst_id, dst_type)
    return f"[ {src_ref} ] -({rel})> {{ {dst_ref} }}"


def generate_storm(conn: sqlite3.Connection) -> str:
    """Generate the full .storm text for every group/vuln/tool/technique node
    and the real edges connecting them.

    Args:
        conn: An open sqlite3.Connection from store.get_connection.

    Returns:
        The complete Storm script as a string, starting with a generated-by
        comment carrying today's date (spec section 8.1's own worked
        example format).
    """
    generated_at = datetime.now(UTC).date().isoformat()
    lines = [f"// generated by strata export storm -- {generated_at}", ""]

    node_placeholders = ",".join("?" for _ in _NODE_TYPES)
    node_rows = conn.execute(
        f"SELECT id, type, label FROM node WHERE type IN ({node_placeholders}) ORDER BY type, id",
        _NODE_TYPES,
    ).fetchall()
    node_types: dict[str, str] = {row["id"]: row["type"] for row in node_rows}

    for row in node_rows:
        lines.append(_node_block(row["id"], row["type"], row["label"]))
        lines.append("")

    edge_placeholders = ",".join("?" for _ in _EDGE_TYPES)
    edge_rows = conn.execute(
        f"SELECT type, src_id, dst_id, note FROM edge "
        f"WHERE type IN ({edge_placeholders}) ORDER BY type, src_id, dst_id",
        _EDGE_TYPES,
    ).fetchall()

    for row in edge_rows:
        src_type = node_types.get(row["src_id"])
        dst_type = node_types.get(row["dst_id"])
        if src_type is None or dst_type is None:
            # Defensive: an edge referencing a node outside this export's
            # four node types is skipped, not guessed at -- this generator
            # only knows how to form-reference group/vuln/tool/technique.
            continue
        if row["note"]:
            lines.append(f"// evidence: {row['note']}")
        lines.append(_edge_block(row["type"], row["src_id"], src_type, row["dst_id"], dst_type))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def validate_storm_grammar(text: str) -> bool:
    """A small grammar-shape assertion, not a real Storm parser (out of scope).

    Checks: every `[`/`]` pair balances, every `{`/`}` pair balances, and
    every non-comment, non-blank line either starts a node/edge block
    matching the expected shape or is a continuation (`:prop=...`) line.
    """
    if text.count("[") != text.count("]"):
        return False
    if text.count("{") != text.count("}"):
        return False

    stripped_lines = [
        line for line in text.splitlines() if line.strip() and not line.strip().startswith("//")
    ]
    if not stripped_lines:
        return False

    block_start_re = re.compile(r"^\[\s*[\w:.]+=\(")
    prop_line_re = re.compile(r"^\s*:\w+=")
    edge_re = re.compile(r"^\[.*\]\s*-\(\S+\)>\s*\{.*\}\s*$")
    close_re = re.compile(r"^\]\s*$")

    for line in stripped_lines:
        if (
            block_start_re.match(line)
            or prop_line_re.match(line)
            or edge_re.match(line)
            or close_re.match(line)
        ):
            continue
        return False
    return True
